version: '3.3'
services:
  dns:
    image: sameersbn/bind
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 10000
        published: 10000
        mode: host
    volumes:
      - ./stack/bind/:/data/bind/etc/
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      ROOT_PASSWORD: verysecurepassword
    networks:
      - outside
  dhcp:
    image: networkboot/dhcpd
    ports:
      - target: 67
        published: 67
        protocol: tcp
        mode: host
      - target: 68
        published: 68
        protocol: tcp
        mode: host
    volumes:
      - ./stack/isc:/data
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - outside
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./stack/nginx/conf/conf.d/web11.conf:/etc/nginx/conf.d/web11.conf:ro
      - ./stack/nginx/conf/conf.d/web22.conf:/etc/nginx/conf.d/web22.conf:ro
      - ./stack/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./stack/nginx/www:/var/www:ro
      - ./stack/cert_ssl:/shared/ssl:ro
      - ./stack/users/passwd:/shared/users/passwd:ro
      - ./stack/users/groups:/shared/users/groups:ro
      - logs:/logs:rw
    deploy:
      restart_policy:
        condition: on-failure
  sftp:
    image: atmoz/sftp
    ports:
        - target: 22
          published: 23
          protocol: tcp
          mode: host
    volumes:
        # SSH connection keys
        - "./stack/key_ssh/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro"
        - "./stack/key_ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro"
        - "./stack/key_ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro"
        - "./stack/key_ssh/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro"

        # USERS
        # User_list
        - "./stack/sftp_users.conf:/etc/sftp/users.conf:ro"
        - "./stack/nginx/www/web11/html/shared:/home/a/shared_web/:rw"
        - "./stack/nginx/www/web11/html/shared:/home/b/shared_web/:rw"
        - "./stack/shared_dir:/home/a/shared_dir/:rw"
        - "./stack/shared_dir:/home/b/shared_dir/:rw"
  postfix_srv:
    image: classcat/postfix-dovecot
    ports:
      - 2022:22
      - 25:25
      - 110:110
      - 143:143
    environment:
      ROOT_PASSWORD: mypassword
      HOSTNAME: mail.ofa.itb
      DOMAINNAME: ofa.itb
      USERS: profe:chequejant,alumne:a
    volumes:
      - ./stack/postfix/mail:/etc/postfix/mail
    networks:
      - outside

networks:
  outside:
    external:
      name: "host"
volumes:
  logs: