version: "3.3"
services:
  postfix_srv:
    container_name: postfix
    image: classcat/postfix-dovecot
    ports:
      - "2022:22"
      - "25:25"
      - "110:110"
      - "143:143"
    environment:
      ROOT_PASSWORD: mypassword
      HOSTNAME: carter.ofa.itb
      DOMAINNAME: ofa.itb
      USERS: alumne:a,a:a,b:b,profe:chequejant
    volumes:
      - "./stack/postfix/mail:/etc/postfix/mail:rw"
      - "./stack/nginx/www/web11/html/privatefolder/logs/postfix/mail.log:/var/log/mail.log:rw"
      - "./stack/nginx/www/web11/html/privatefolder/logs/postfix/mail.err:/var/log/mail.err:rw"
      - "./stack/nginx/www/web11/html/privatefolder/logs/postfix/spamassasin:/var/log/spamassasin:rw"
      - "./stack/nginx/www/web11/html/privatefolder/logs/postfix/supervisor:/var/log/supervisor:rw"
networks:
  outside:
    external:
      name: "host"
